[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'vimproc.vim']
on_cmd = ['Unite', 'UniteWithCursorWord', 'UniteWithInput', 'UniteWithBufferDir']
hook_source = 'call beans15#init#source_rc("/plugins/unite.rc.vim")'
hook_add = 'call beans15#init#source_rc("/plugins/unite.add.rc.vim")'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'beans15/unite-maven'
depends = ['unite.vim', 'webapi-vim']
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
on_map = [['n', '<Plug>']]
on_cmd = ['VimFiler', 'VimFilerExplorer', 'VimFilerBufferDir', 'VimFilerTab', 'VimFilerCreate']
hook_source = 'call beans15#init#source_rc("/plugins/vimfiler.rc.vim")'
hook_add = 'call beans15#init#source_rc("/plugins/vimfiler.add.rc.vim")'

[[plugins]]
repo = 'Shougo/vimshell'
depends = 'vimproc.vim'
on_cmd = ['VimShell', 'VimShellPop', 'VimShellTab', 'VimShellInteractive', 'VimShellBufferDir']
hook_add = 'call beans15#init#source_rc("/plugins/vimshell.add.rc.vim")'
hook_source = '''
  let g:vimshell_force_overwrite_statusline = 0

  if g:portable
    let g:vimshell_data_directory = expand('$VIM/.vimshell')
  endif
'''

[[plugins]]
repo = 'supermomonga/vimshell-pure.vim'
depends = 'vimshell'
on_source = 'vimshell'

[[plugins]]
repo = 'sudo.vim'
if = 'executable("sudo")'
on_cmd = ['SudoRead', 'SudoWrite']

[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = 'Ref'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = [['n', '<Plug>']]
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]
repo = 'scrooloose/syntastic'
on_cmd = 'SyntasticCheck'
hook_source = '''
  let g:syntastic_mode_map = {
  \ 'mode': 'passive',
  \ 'active_filetypes': [],
  \ 'passive_filetypes': [] }
  let g:syntastic_always_populate_loc_list = 1
'''
hook_add = 'nnoremap <silent> <Leader>L :<C-u>SyntasticCheck<CR>'

[[plugins]]
repo = 'gregsexton/gitv'
depends = 'vim-fugitive'
on_cmd = 'Gitv'
hook_add = 'call beans15#init#source_rc("/plugins/gitv.add.rc.vim")'

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
if = 'executable("curl")'
on_cmd = 'Gist'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-coffee-script'
on_ft = 'coffee'
hook_source = '''
  " 無名関数でラップしない
  g:coffee_make_options = '-b'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'php']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
if = 'executable("ghc-mod")'
on_ft = 'haskell'

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = 'js'
