#!/bin/sh

# Setup the setting files to the local machine.

cat .exclude .exclude-local 2> /dev/null > .exclude-all
rsync -auvzrK --delete $* --files-from=.files --exclude-from=.exclude-all ./ ~
rm .exclude-all

# Clone 
if [[ ! -d ~/.vim/bundle/neobundle.vim ]]; then
    git clone git://github.com/Shougo/neobundle.vim.git ~/.vim/bundle/neobundle.vim
fi
