#!/usr/bin/env zsh
# This hook is run after every virtualenv is deactivated.

# 環境ごとの設定を呼び出す
site_command="$WORKON_HOME/${VIRTUAL_ENV_NAME}.postdeactivate"
if [[ -e $site_command ]]; then
    source $site_command
fi
