#!/usr/bin/env zsh
# This hook is run after every virtualenv is deactivated.

RPROMPT=$_OLD_RPROMPT

# 環境ごとの設定を呼び出す
site_command="$WORKON_HOME/postdeactivate.$VIRTUAL_ENV_NAME"
if [[ -e $site_command ]]; then
    source $site_command
fi
