#!/opt/local/bin/zsh
# This hook is run after every virtualenv is deactivated.

VIRTUAL_ENV_NAME=`basename "$VIRTUAL_ENV"`

RPROMPT=$_OLD_RPROMPT

# 環境ごとの設定を呼び出す
site_command="$WORKON_HOME/postdeactivate-$VIRTUAL_ENV_NAME"
if [[ -e $site_command ]]; then
    source $site_command
fi
