#!/usr/bin/env zsh
# This hook is run after every virtualenv is activated.

VIRTUAL_ENV_NAME=`basename "$VIRTUAL_ENV"`

# プロンプトの設定
_OLD_RPROMPT=$RPROMPT
RPROMPT="%{${fg_bold[white]}%}(env: %{${fg[green]}%}$VIRTUAL_ENV_NAME%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"

# 環境ごとの設定を呼び出す
site_command="$WORKON_HOME/${VIRTUAL_ENV_NAME}.postactivate"
if [[ -e $site_command ]]; then
    source $site_command
fi
